import type { SectionVisibility, StartupDigitalTwin } from "@/types/digital-twin";

/**
 * Isolated demo Digital Twin dataset — two startups with materially
 * different stages, completion levels, traction, funding, goals, risks and
 * milestones, specifically so startup switching/isolation can be verified.
 * Nothing here is real. Read through lib/services/digital-twin.ts only.
 */

function defaultVisibility(): SectionVisibility {
  return {
    identity: "public",
    founders: "aff_team",
    team: "aff_team",
    problem: "public",
    product: "public",
    market: "investors",
    businessModel: "investors",
    traction: "investors",
    financials: "private",
    funding: "investors",
    impact: "public",
    goals: "aff_team",
    risks: "private",
    milestones: "public",
  };
}

const wakamaTwin: StartupDigitalTwin = {
  identity: {
    name: "Wakama",
    tagline: "AgriTech marketplace connecting smallholder farmers to buyers",
    shortDescription:
      "Wakama helps smallholder farmers in Côte d'Ivoire sell directly to urban buyers and processors, cutting out unreliable middlemen.",
    longDescription:
      "Wakama operates a mobile-first marketplace and logistics network that lets smallholder farmers list produce, get fair prices, and access buyers they could never reach on their own. We combine aggregation points, shared transport, and simple digital tools designed for low-connectivity areas.",
    website: "https://wakama.africa",
    foundedYear: 2024,
    country: "Côte d'Ivoire",
    city: "Abidjan",
    operatingCountries: ["Côte d'Ivoire"],
    industry: "AgriTech",
    subIndustry: "Agricultural marketplaces",
    stage: "mvp",
    registration: { status: "in_progress", country: "Côte d'Ivoire" },
    preferredCurrency: "XOF",
  },
  founders: [
    {
      id: "wakama-founder-1",
      firstName: "Amara",
      lastName: "Diallo",
      role: "Co-Founder & CEO",
      email: "amara@wakama.africa",
      linkedin: "https://linkedin.com/in/amaradiallo",
      country: "Côte d'Ivoire",
      bio: "Former agricultural supply chain analyst turned founder, born and raised in a farming family outside Abidjan.",
      status: "active",
      engagement: "full_time",
      ownershipPct: 55,
      isPrimaryContact: true,
    },
    {
      id: "wakama-founder-2",
      firstName: "Yao",
      lastName: "Koffi",
      role: "Co-Founder & CTO",
      country: "Côte d'Ivoire",
      status: "active",
      engagement: "full_time",
      ownershipPct: 30,
      isPrimaryContact: false,
    },
  ],
  team: [
    {
      id: "wakama-team-1",
      name: "Fatou Bamba",
      role: "Field Operations Lead",
      department: "Operations",
      engagement: "full_time",
      startDate: "2024-06-01",
      expertise: ["Farmer relations", "Logistics"],
    },
  ],
  problem: {
    statement: "Smallholder farmers lose 20-30% of potential income to unreliable middlemen and price opacity.",
    targetCustomer: "Smallholder farmers producing cassava, plantain and vegetables within 150km of Abidjan.",
    currentAlternatives: "Local intermediaries ('pisteurs') who set prices with little transparency.",
    painSeverity: "high",
    evidence: "40 farmer interviews across 3 regions confirmed consistent price volatility complaints.",
  },
  product: {
    name: "Wakama Marketplace",
    type: "marketplace",
    description: "A mobile-first marketplace pairing farmer supply listings with verified buyers, plus shared transport booking.",
    developmentStage: "mvp",
    valueProposition: "Fair, transparent prices and guaranteed buyers without needing a smartphone or reliable data connection.",
    coreFeatures: [
      "USSD listing for feature phones",
      "Buyer matching",
      "Shared transport booking",
      "Price transparency dashboard",
    ],
    technology: "USSD + lightweight Android app, Node.js backend",
    ipStatus: "not_applicable",
    launched: true,
    launchDate: "2025-02-01",
    demoUrl: "https://wakama.africa/demo",
  },
  market: {
    primaryMarket: "Smallholder agricultural trade in Côte d'Ivoire",
    customerSegments: ["Smallholder farmers", "Urban wholesale buyers", "Food processors"],
    geographies: ["Côte d'Ivoire"],
    tam: {
      amount: { amount: 1_200_000_000, currency: "USD" },
      methodology: "Top-down: national smallholder agricultural output value",
    },
    trends: "Growing urban demand for traceable local produce; mobile money penetration accelerating rural digital adoption.",
    competitors: [{ id: "wakama-comp-1", name: "Local pisteurs (informal intermediaries)", notes: "Fragmented, no digital tooling" }],
    competitiveAdvantage: "Only platform combining USSD accessibility with shared logistics in the region.",
  },
  businessModel: {
    types: ["marketplace"],
    revenueStreams: [{ id: "wakama-rev-1", label: "Transaction commission (5%)" }],
    pricingModel: "Commission per completed transaction",
    salesChannels: ["Field agents", "Farmer cooperatives"],
    distributionModel: "Direct + cooperative partnerships",
    keyPartnerships: ["Regional farmer cooperatives"],
  },
  traction: {
    metrics: [
      { id: "wakama-tm-1", type: "active_users", label: "Active farmers", value: 340, unit: "farmers", date: "2026-09-01", verified: false },
      {
        id: "wakama-tm-2",
        type: "gmv",
        label: "Monthly GMV",
        value: 18500,
        unit: "USD",
        currency: "USD",
        period: "2026-08",
        date: "2026-09-01",
        verified: false,
      },
      { id: "wakama-tm-3", type: "pilots", label: "Active pilot regions", value: 3, unit: "regions", date: "2026-09-01", verified: false },
    ],
    narrative: "Piloting in 3 regions around Abidjan; word-of-mouth adoption among cooperatives outpacing paid acquisition.",
    majorCustomers: ["Cooperative Agricole du Sud"],
  },
  financials: {
    currency: "XOF",
    monthlyRevenue: 620_000,
    monthlyExpenses: 2_100_000,
    monthlyBurn: 1_480_000,
    cashBalance: 9_500_000,
    runwayMonths: 6,
    profitable: false,
    financialYear: 2026,
  },
  funding: {
    status: "raising",
    totalRaised: { amount: 45000, currency: "USD" },
    currentRound: "Pre-seed",
    targetRaise: { amount: 250000, currency: "USD" },
    minimumTicket: { amount: 10000, currency: "USD" },
    instrument: "safe",
    previousRounds: [
      {
        id: "wakama-round-1",
        date: "2024-11-01",
        roundType: "Friends & Family",
        amount: { amount: 45000, currency: "USD" },
        investorNames: [],
      },
    ],
    useOfFunds: "Expand field agent network and extend to 2 additional regions.",
  },
  impact: {
    enabled: true,
    thesis: "Increasing smallholder farmer income directly reduces rural poverty and strengthens local food security.",
    sdgs: ["SDG 1: No Poverty", "SDG 2: Zero Hunger"],
    beneficiaries: 340,
    jobsCreated: 6,
    metrics: [],
  },
  goals: [
    {
      id: "wakama-goal-1",
      title: "Reach 1,000 active farmers",
      category: "growth",
      targetDate: "2027-03-01",
      status: "in_progress",
      progressPct: 34,
      targetValue: 1000,
      currentValue: 340,
      unit: "farmers",
    },
    {
      id: "wakama-goal-2",
      title: "Close pre-seed round",
      category: "fundraising",
      targetDate: "2026-12-15",
      status: "in_progress",
      progressPct: 18,
      targetValue: 250000,
      currentValue: 45000,
      unit: "USD",
    },
  ],
  risks: [
    {
      id: "wakama-risk-1",
      title: "Seasonal demand volatility",
      category: "market",
      probability: "medium",
      impact: "high",
      mitigation: "Diversifying crop categories beyond cassava.",
      status: "open",
    },
    {
      id: "wakama-risk-2",
      title: "Field agent turnover",
      category: "operations",
      probability: "medium",
      impact: "medium",
      status: "open",
    },
  ],
  milestones: [
    { id: "wakama-ms-1", title: "Company founded", date: "2024-03-01", category: "company", status: "achieved" },
    { id: "wakama-ms-2", title: "MVP launched", date: "2025-02-01", category: "product", status: "achieved" },
    { id: "wakama-ms-3", title: "First pilot region live", date: "2025-06-01", category: "traction", status: "achieved" },
  ],
  visibility: defaultVisibility(),
  onboarding: { completed: true, currentStep: 12 },
};

const solariTwin: StartupDigitalTwin = {
  identity: {
    name: "Solari",
    tagline: "Pay-as-you-go solar financing for last-mile households",
    shortDescription: "Solari provides affordable, mobile-money-financed solar home systems to households beyond the grid in Kenya.",
    longDescription:
      "Solari distributes solar home systems through a pay-as-you-go model powered by mobile money, targeting rural and peri-urban households without reliable grid access. Our IoT-enabled units allow remote monitoring and flexible repayment.",
    website: "https://solari.energy",
    foundedYear: 2023,
    country: "Kenya",
    city: "Nairobi",
    operatingCountries: ["Kenya", "Uganda"],
    industry: "CleanTech",
    subIndustry: "Off-grid energy",
    stage: "early_traction",
    legalStatus: "Private Limited Company",
    registration: { status: "registered", country: "Kenya", number: "PVT-KE-2023-04821" },
    preferredCurrency: "KES",
  },
  founders: [
    {
      id: "solari-founder-1",
      firstName: "Njeri",
      lastName: "Wanjiru",
      role: "Co-Founder & CEO",
      email: "njeri@solari.energy",
      phone: "+254700000000",
      linkedin: "https://linkedin.com/in/njeriwanjiru",
      country: "Kenya",
      bio: "10 years in renewable energy financing across East Africa.",
      status: "active",
      engagement: "full_time",
      ownershipPct: 48,
      isPrimaryContact: true,
    },
    {
      id: "solari-founder-2",
      firstName: "David",
      lastName: "Otieno",
      role: "Co-Founder & COO",
      email: "david@solari.energy",
      linkedin: "https://linkedin.com/in/davidotieno",
      country: "Kenya",
      bio: "Previously scaled last-mile distribution for an FMCG company.",
      status: "active",
      engagement: "full_time",
      ownershipPct: 32,
      isPrimaryContact: false,
    },
  ],
  team: [
    {
      id: "solari-team-1",
      name: "Grace Achieng",
      role: "Head of Credit Risk",
      department: "Finance",
      engagement: "full_time",
      startDate: "2024-02-01",
      expertise: ["Credit scoring", "Mobile money"],
    },
    {
      id: "solari-team-2",
      name: "Peter Mwangi",
      role: "Field Operations Manager",
      department: "Operations",
      engagement: "full_time",
      startDate: "2023-09-01",
      expertise: ["Last-mile distribution"],
    },
  ],
  problem: {
    statement: "70% of rural Kenyan households lack reliable grid electricity and cannot afford solar systems upfront.",
    targetCustomer: "Rural and peri-urban households earning $3-8/day without grid access.",
    currentAlternatives: "Kerosene lamps, disposable battery torches, or expensive diesel generators.",
    painSeverity: "critical",
    evidence: "Pilot of 500 households showed 95% retention after 6 months of PAYG repayment.",
    whyNow: "Mobile money penetration in Kenya now exceeds 80%, making micro-repayment logistically viable at scale.",
  },
  product: {
    name: "Solari Home Kit",
    type: "hardware",
    description: "IoT-enabled solar home system with lighting, phone charging and radio, unlocked via mobile money micro-payments.",
    developmentStage: "live",
    valueProposition: "Reliable power from day one, paid for in small increments households can actually afford.",
    coreFeatures: [
      "Remote IoT lock/unlock",
      "Mobile money integration",
      "3-light + phone charging kit",
      "Usage analytics for credit scoring",
    ],
    technology: "Custom IoT hardware, M-Pesa API integration",
    ipStatus: "pending",
    launched: true,
    launchDate: "2024-01-15",
    demoUrl: "https://solari.energy/product",
  },
  market: {
    primaryMarket: "Off-grid household energy in East Africa",
    customerSegments: ["Off-grid rural households", "Peri-urban households with unreliable grid"],
    geographies: ["Kenya", "Uganda"],
    tam: { amount: { amount: 2_500_000_000, currency: "USD" }, methodology: "Off-grid solar market sizing, GOGLA regional reports" },
    sam: { amount: { amount: 400_000_000, currency: "USD" }, methodology: "Kenya + Uganda unelectrified households x average system value" },
    som: { amount: { amount: 12_000_000, currency: "USD" }, methodology: "3-year realistic penetration based on current distribution capacity" },
    trends: "Falling solar hardware costs and expanding mobile money agent networks.",
    competitors: [
      { id: "solari-comp-1", name: "M-KOPA", notes: "Larger, more capitalized incumbent" },
      { id: "solari-comp-2", name: "d.light", notes: "Hardware-focused, weaker fintech layer" },
    ],
    competitiveAdvantage: "Best-in-class credit risk model built on 2 years of proprietary repayment data.",
  },
  businessModel: {
    types: ["b2c"],
    revenueStreams: [
      { id: "solari-rev-1", label: "Pay-as-you-go daily fees" },
      { id: "solari-rev-2", label: "Buyout / ownership transfer fee" },
    ],
    pricingModel: "Daily micro-payment via mobile money, ownership after 18 months",
    averageRevenuePerCustomer: { amount: 0.45, currency: "USD" },
    salesChannels: ["Direct field agents", "Community agent network"],
    salesCycle: "1-2 days from demo to activation",
    distributionModel: "Agent-led door-to-door with community demos",
    keyPartnerships: ["Safaricom M-Pesa", "Local SACCOs"],
  },
  traction: {
    metrics: [
      {
        id: "solari-tm-1",
        type: "active_customers",
        label: "Active households",
        value: 8600,
        unit: "households",
        date: "2026-09-01",
        verified: true,
        source: "Internal billing system",
      },
      { id: "solari-tm-2", type: "mrr", label: "MRR", value: 41000, unit: "USD", currency: "USD", period: "2026-08", date: "2026-09-01", verified: true },
      { id: "solari-tm-3", type: "retention", label: "12-month retention", value: 91, unit: "%", date: "2026-09-01", verified: true },
      { id: "solari-tm-4", type: "churn", label: "Monthly churn", value: 2.1, unit: "%", date: "2026-09-01", verified: false },
    ],
    narrative: "Consistent month-over-month growth since the seed round closed; retention holding above 90% for 4 consecutive quarters.",
    majorCustomers: [],
    commercialEvidence: "Signed distribution MoU with 3 SACCOs covering 40,000 potential households.",
  },
  financials: {
    currency: "USD",
    annualRevenue: 380000,
    monthlyRevenue: 41000,
    monthlyExpenses: 52000,
    monthlyBurn: 11000,
    cashBalance: 210000,
    runwayMonths: 19,
    profitable: false,
    financialYear: 2026,
    notes: "Approaching operating breakeven in core Nairobi region; Uganda expansion still burn-negative.",
  },
  funding: {
    status: "raising",
    totalRaised: { amount: 1_200_000, currency: "USD" },
    currentRound: "Seed extension",
    targetRaise: { amount: 1_500_000, currency: "USD" },
    minimumTicket: { amount: 50000, currency: "USD" },
    maximumTicket: { amount: 500000, currency: "USD" },
    valuation: { amount: 9_000_000, currency: "USD" },
    instrument: "equity",
    previousRounds: [
      { id: "solari-round-1", date: "2023-08-01", roundType: "Pre-seed", amount: { amount: 200000, currency: "USD" }, investorNames: ["Savannah Angels"] },
      {
        id: "solari-round-2",
        date: "2024-11-01",
        roundType: "Seed",
        amount: { amount: 1_000_000, currency: "USD" },
        investorNames: ["GreenGrid Capital", "Savannah Angels"],
        notes: "Led by GreenGrid Capital",
      },
    ],
    useOfFunds: "Scale Uganda operations and expand credit facility for hardware inventory.",
  },
  impact: {
    enabled: true,
    thesis: "Displacing kerosene and diesel with clean, affordable power reduces household energy poverty and emissions.",
    sdgs: ["SDG 7: Affordable and Clean Energy", "SDG 1: No Poverty", "SDG 13: Climate Action"],
    beneficiaries: 34400,
    jobsCreated: 45,
    womenBeneficiariesPct: 54,
    youthBeneficiariesPct: 38,
    environmentalImpact: "Estimated 1,200 tonnes of CO2e displaced annually versus kerosene baseline.",
    socialImpact: "Extended study/business hours reported by 78% of surveyed households.",
    metrics: [],
  },
  goals: [
    {
      id: "solari-goal-1",
      title: "Reach 20,000 active households",
      category: "growth",
      targetDate: "2027-06-01",
      status: "in_progress",
      progressPct: 43,
      targetValue: 20000,
      currentValue: 8600,
      unit: "households",
    },
    {
      id: "solari-goal-2",
      title: "Close $1.5M seed extension",
      category: "fundraising",
      targetDate: "2026-12-01",
      status: "in_progress",
      progressPct: 22,
      targetValue: 1500000,
      currentValue: 330000,
      unit: "USD",
    },
    {
      id: "solari-goal-3",
      title: "Launch in Uganda's second region",
      category: "market",
      status: "not_started",
      progressPct: 0,
    },
  ],
  risks: [
    {
      id: "solari-risk-1",
      title: "Currency depreciation exposure (KES/UGX vs USD funding)",
      category: "financial",
      probability: "medium",
      impact: "high",
      mitigation: "Hedging via local-currency revenue matching.",
      status: "open",
    },
    {
      id: "solari-risk-2",
      title: "Mobile money regulatory changes",
      category: "regulatory",
      probability: "low",
      impact: "high",
      mitigation: "Active engagement with Central Bank of Kenya sandbox.",
      status: "mitigated",
    },
    {
      id: "solari-risk-3",
      title: "Hardware supply chain delays",
      category: "operations",
      probability: "medium",
      impact: "medium",
      status: "open",
    },
  ],
  milestones: [
    { id: "solari-ms-1", title: "Company founded", date: "2023-05-01", category: "company", status: "achieved" },
    { id: "solari-ms-2", title: "Product launched", date: "2024-01-15", category: "product", status: "achieved" },
    { id: "solari-ms-3", title: "Pre-seed closed", date: "2023-08-01", category: "funding", status: "achieved" },
    { id: "solari-ms-4", title: "Seed round closed", date: "2024-11-01", category: "funding", status: "achieved" },
    { id: "solari-ms-5", title: "8,000th household connected", date: "2026-07-01", category: "traction", status: "achieved" },
    { id: "solari-ms-6", title: "Uganda expansion launch", date: "2026-12-01", category: "traction", status: "planned" },
  ],
  visibility: defaultVisibility(),
  onboarding: { completed: true, currentStep: 12 },
};

export const demoDigitalTwins: Record<string, StartupDigitalTwin> = {
  "startup-wakama": wakamaTwin,
  "startup-solari": solariTwin,
};
